name: Slate

include:
  - path: project.local.yml

options:
  bundleIdPrefix: com.damsac.slate
  deploymentTarget:
    iOS: "17.0"

  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

targets:
  Slate:
    type: application
    platform: iOS
    sources:
      - path: Slate
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER_SLATE)
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: Slate/Slate.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: true
    info:
      path: Slate/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        AppGroupIdentifier: "$(APP_GROUP_IDENTIFIER)"
    entitlements:
      path: Slate/Slate.entitlements
      properties:
        com.apple.security.application-groups:
          - $(APP_GROUP_IDENTIFIER)
    dependencies:
      - target: TodoWidgetExtension
    scheme:
      testTargets:
        - SlateTests

  SlateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SlateTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Slate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER_TESTS)
        GENERATE_INFOPLIST_FILE: true

  TodoWidgetExtension:
    type: app-extension
    platform: iOS
    product: TodoWidgetExtension
    sources:
      - path: SlateWidget
        excludes:
          - "**/.DS_Store"
      # Shared sources the widget needs
      - path: Slate/Models/TodoItem.swift
      - path: Slate/Shared/PersistenceConfig.swift
      - path: Slate/Theme/Theme.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER_WIDGET)
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_ENTITLEMENTS: SlateWidget/SlateWidget.entitlements
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        SWIFT_EMIT_LOC_STRINGS: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: SlateWidget/SlateWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - $(APP_GROUP_IDENTIFIER)
    info:
      path: SlateWidget/Info.plist
      properties:
        CFBundleDisplayName: Slate Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
